---

- name: check if repository is valid
  assert:
    that:
      - phoenix_app_repository | length > 0
  when: phoenix_app_repository is defined


- name: check config syntax is valid
  assert:
    that:
      - item.file is defined
      - item.content is defined
  with_items: phoenix_app_configs
